name: prerelease

on:
  push:
    tags:
      - 'v*ALPHA*'
      - 'v*BETA*'
      - 'v*RC*'
  workflow_dispatch:

jobs:
  release:
    uses: mrgoodbytes8667/workflows/.github/workflows/release.yml@php8.1-8.2
    with:
      phpUnitVersion: 10.0
      prerelease: true